import { useEffect, useState } from 'react';
import { type AcademicNote, type PortalRole, portalService } from '../features/portal/service';
import './AccountPages.css';

const blank = { subjectCode: '', title: '', description: '', course: '', department: '', semester: 1, status: 'draft' as 'draft' | 'published' };

export default function PortalPage() {
  const [role, setRole] = useState<PortalRole | null>(null);
  const [notes, setNotes] = useState<AcademicNote[]>([]);
  const [subjects, setSubjects] = useState<Array<{ id: string; subjectCode: string; course: string; department: string; semester: number | null }>>([]);
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState<AcademicNote | null>(null); const [file, setFile] = useState<File | undefined>();
  const [teacherEmail, setTeacherEmail] = useState(''); const [teacherId, setTeacherId] = useState(''); const [message, setMessage] = useState('');
  const load = async () => {
    try { const currentRole = await portalService.role(); setRole(currentRole); setNotes(await portalService.notes()); if (currentRole === 'teacher') setSubjects(await portalService.teacherSubjects()); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load the portal.'); }
  };
  useEffect(() => { void load(); }, []);
  const save = async () => {
    if (!editing && !file) return setMessage('Choose a note file before saving a new note.');
    try { await portalService.saveNote(form, file, editing?.id); setMessage(editing ? 'Academic note updated.' : 'Academic note saved.'); setForm(blank); setFile(undefined); setEditing(null); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save academic note.'); }
  };
  const edit = (note: AcademicNote) => { setEditing(note); setFile(undefined); setForm({ subjectCode: note.subjectCode, title: note.title, description: note.description, course: note.course, department: note.department, semester: note.semester, status: note.status }); };
  if (!role) return <section className="account-page"><p>Loading portal…</p>{message && <p className="account-message">{message}</p>}</section>;
  if (role === 'student') return <section className="account-page"><h1>Teacher/Admin Portal</h1><p>This page is available only to teacher and admin accounts. Student access to permitted published notes is available in Study AI.</p></section>;
  return <section className="account-page"><header><h1>{role === 'admin' ? 'Admin Portal' : 'Teacher Portal'}</h1><p>CampusFlow’s shared academic-note workspace.</p></header>{message && <p className="account-message" role="status">{message}</p>}
    {role === 'teacher' && <><section className="account-card"><h2>{editing ? 'Edit academic note' : 'Upload academic note'}</h2><div className="account-grid"><label>Assigned subject<select value={form.subjectCode} onChange={(event) => setForm({ ...form, subjectCode: event.target.value })}><option value="">Select subject</option>{subjects.map((subject) => <option key={subject.id} value={subject.subjectCode}>{subject.subjectCode}</option>)}</select></label><label>Title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Course<input value={form.course} onChange={(event) => setForm({ ...form, course: event.target.value })} /></label><label>Department<input value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} /></label><label>Semester<input type="number" min="1" max="20" value={form.semester} onChange={(event) => setForm({ ...form, semester: Number(event.target.value) })} /></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as 'draft' | 'published' })}><option value="draft">Draft</option><option value="published">Publish</option></select></label></div><label>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>{editing ? 'Replace file (optional)' : 'File'}<input type="file" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0])} /></label><div className="account-actions"><button onClick={() => void save()}>{editing ? 'Save changes' : 'Save note'}</button>{editing && <button onClick={() => { setEditing(null); setForm(blank); setFile(undefined); }}>Cancel edit</button>}</div></section><section className="account-card"><h2>My uploaded notes</h2>{notes.length ? notes.map((note) => <article className="document-list" key={note.id}><div><strong>{note.title}</strong><p>{note.subjectCode} · {note.status} · {note.fileName}</p></div><div className="account-actions"><button onClick={() => edit(note)}>Edit</button><button className="danger" onClick={() => void portalService.deleteOwnNote(note.id).then(load).catch((error) => setMessage(error.message))}>Delete</button></div></article>) : <p className="account-empty">No notes uploaded yet.</p>}</section></>}
    {role === 'admin' && <><section className="account-card"><h2>Invite teacher</h2><label>Email<input type="email" value={teacherEmail} onChange={(event) => setTeacherEmail(event.target.value)} /></label><button onClick={() => void portalService.inviteTeacher(teacherEmail).then((data) => { setMessage(`Teacher invited. ID: ${data.teacherId}`); setTeacherId(data.teacherId); }).catch((error) => setMessage(error.message))}>Invite teacher</button></section><section className="account-card"><h2>Assign subject</h2><div className="account-grid"><label>Teacher ID<input value={teacherId} onChange={(event) => setTeacherId(event.target.value)} /></label><label>Subject code<input value={form.subjectCode} onChange={(event) => setForm({ ...form, subjectCode: event.target.value })} /></label><label>Course<input value={form.course} onChange={(event) => setForm({ ...form, course: event.target.value })} /></label><label>Department<input value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} /></label><label>Semester<input type="number" min="1" max="20" value={form.semester} onChange={(event) => setForm({ ...form, semester: Number(event.target.value) })} /></label></div><button onClick={() => void portalService.assignTeacherSubject(teacherId, form.subjectCode, form.course, form.department, form.semester).then(() => setMessage('Subject assigned.')).catch((error) => setMessage(error.message))}>Assign subject</button></section><section className="account-card"><h2>All academic notes</h2>{notes.map((note) => <article className="document-list" key={note.id}><div><strong>{note.title}</strong><p>{note.subjectCode} · {note.status} · {note.fileName}</p></div><button className="danger" onClick={() => void portalService.removeAcademicNote(note.id).then(load).catch((error) => setMessage(error.message))}>Remove</button></article>)}</section></>}
  </section>;
}
