/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RescheduleRouteImport } from './routes/reschedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthGoogleCallbackRouteImport } from './routes/oauth.google.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RescheduleRoute = RescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCallbackRoute = OauthGoogleCallbackRouteImport.update({
  id: '/oauth/google/callback',
  path: '/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reschedule': typeof RescheduleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reschedule': typeof RescheduleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reschedule': typeof RescheduleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/plan'
    | '/preferences'
    | '/profile'
    | '/reschedule'
    | '/reset-password'
    | '/sitemap.xml'
    | '/oauth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/plan'
    | '/preferences'
    | '/profile'
    | '/reschedule'
    | '/reset-password'
    | '/sitemap.xml'
    | '/oauth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/plan'
    | '/preferences'
    | '/profile'
    | '/reschedule'
    | '/reset-password'
    | '/sitemap.xml'
    | '/oauth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  RescheduleRoute: typeof RescheduleRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OauthGoogleCallbackRoute: typeof OauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule': {
      id: '/reschedule'
      path: '/reschedule'
      fullPath: '/reschedule'
      preLoaderRoute: typeof RescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google/callback': {
      id: '/oauth/google/callback'
      path: '/oauth/google/callback'
      fullPath: '/oauth/google/callback'
      preLoaderRoute: typeof OauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  RescheduleRoute: RescheduleRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OauthGoogleCallbackRoute: OauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
