module.exports = {
  Users: require('./User'),
  UserProfiles: require('./UserProfile'),
  Mentors: require('./Mentor'),
  Subjects: require('./Subject'),
  Topics: require('./Topic'),
  Subtopics: require('./Subtopic'),
  TopicProgress: require('./TopicProgress'),
  Recommendations: require('./Recommendation'),
  Goals: require('./Goal'),
  StudyPlans: require('./StudyPlan'),
  AIPlans: require('./AIPlan'),
  DailyTasks: require('./DailyTask'),
  Progress: require('./Progress'),
  Notifications: require('./Notification'),
  Calendar: require('./CalendarEvent'),
  Chat: require('./Chat'),
  Achievements: require('./Achievement'),
  Quiz: require('./Quiz'),
  QuizAttempts: require('./QuizAttempt'),
};
