/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Server-side AI capability specs: Zod input schemas, prompt builders, and output schemas.
 */

import { z } from "zod";
import { MAX_INPUT_CHARS, type CapabilityId } from "./catalog";

export interface BuiltPrompt {
  system: string;
  prompt: string;
  /** Optional image data URLs to send as vision message content (e.g. Image → Quiz). */
  images?: string[];
}

/** Max base64 image data-URL length accepted by vision capabilities (~6MB encoded). */
export const MAX_IMAGE_DATA_URL_CHARS = 8_000_000;

const imageField = z
  .string()
  .min(1, "Image is required.")
  .max(MAX_IMAGE_DATA_URL_CHARS, "Image is too large — please use a smaller image.")
  .refine(
    (v) => /^data:image\/(png|jpe?g|webp|gif);base64,/.test(v),
    "Image must be a base64 PNG, JPEG, WebP, or GIF data URL."
  );

interface ObjectCapabilitySpec {
  mode: "object";
  inputSchema: z.ZodTypeAny;
  outputSchema: z.ZodTypeAny;
  build: (input: any) => BuiltPrompt;
}

export type CapabilitySpec = ObjectCapabilitySpec;

const textField = z
  .string()
  .min(1, "Text cannot be empty.")
  .max(MAX_INPUT_CHARS, "Text exceeds max length.")
  .refine((val) => val.trim().length > 0, "Text cannot be empty.");

/* Defensive size caps for structured (non-source-text) inputs (STANDARDS §8).
   All sit comfortably above real UI usage (quizzes cap at 30 questions). */
const MAX_PROMPT_CHARS = 4_000;
const MAX_OPTION_CHARS = 2_000;
const MAX_OPTIONS = 10;
const MAX_ACCEPTABLE = 50;
const MAX_ANSWER_CHARS = 4_000;
const MAX_RESULTS = 200;
const MAX_EXISTING_PROMPTS = 200;

const promptField = z.string().min(1, "Question prompt is required.").max(MAX_PROMPT_CHARS);
const optionsField = z.array(z.string().max(MAX_OPTION_CHARS)).max(MAX_OPTIONS);
const acceptableField = z.array(z.string().max(MAX_OPTION_CHARS)).max(MAX_ACCEPTABLE);

const questionTypeSchema = z.enum(["mcq", "tf", "short", "fill"]);
const difficultySchema = z.enum(["easy", "medium", "hard", "mixed"]);
const audienceSchema = z.enum(["school", "university", "professional"]);

/* ------------------------------------------------------------------ */
/* Output Schemas                                                     */
/* ------------------------------------------------------------------ */

// Schema representing a question generated by AI
const aiQuestionSchema = z.object({
  type: questionTypeSchema,
  prompt: z.string().describe("The question text or statement. For fill-in-the-blank, use '_____' to represent the blank."),
  options: z.array(z.string()).describe("List of options. For MCQ, exactly 4 options. For True/False, exactly ['True', 'False']. For short/fill, keep empty."),
  correctIndex: z.number().int().describe("0-based index of correct option. For MCQ/TF, must match the correct option. For short/fill, must be -1."),
  acceptableAnswers: z.array(z.string()).describe("For short/fill questions, list of acceptable exact text answers. For MCQ/TF, keep empty."),
  explanation: z.string().describe("A brief, clear explanation of why the answer is correct based on the source text."),
});

const quizOutputSchema = z.object({
  questions: z.array(aiQuestionSchema),
});

const flashcardOutputSchema = z.object({
  cards: z.array(
    z.object({
      front: z.string().describe("The term, concept, or question on the front of the flashcard."),
      back: z.string().describe("The definition, answer, or explanation on the back of the flashcard."),
    })
  ),
});

const summaryOutputSchema = z.object({
  summary: z.string().describe("A concise summary of the main points in 2-3 paragraphs."),
  concepts: z.array(
    z.object({
      term: z.string().describe("The key concept term."),
      definition: z.string().describe("Clear, concise explanation of the term based on the text."),
    })
  ).describe("A list of the top key concepts extracted from the text."),
});

const explainOutputSchema = z.object({
  hint: z.string().describe("A subtle, helpful hint that guides the user towards the answer without revealing it."),
  explanation: z.string().describe("A detailed, step-by-step explanation of the correct answer and why other options are incorrect."),
});

const weakTopicsOutputSchema = z.object({
  topics: z.array(
    z.object({
      topic: z.string().describe("Name of the topic or concept area."),
      strength: z.enum(["weak", "medium", "strong"]),
      guidance: z.string().describe("Personalized study advice for this topic."),
    })
  ),
  tasks: z.array(z.string()).describe("A list of concrete recommended study tasks to improve in these areas."),
});

/* ------------------------------------------------------------------ */
/* Specs Registry                                                     */
/* ------------------------------------------------------------------ */

export const SPECS: Record<CapabilityId, CapabilitySpec> = {
  quiz: {
    mode: "object",
    inputSchema: z.object({
      text: textField,
      count: z.number().int().min(1).max(30),
      types: z.array(questionTypeSchema).min(1),
      difficulty: difficultySchema,
      audience: audienceSchema,
    }),
    outputSchema: quizOutputSchema,
    build: (input) => ({
      system: `You are an expert quiz generator. Generate a set of ${input.count} questions based ONLY on the provided text.
Difficulty target: ${input.difficulty}.
Target audience level: ${input.audience}.
Allowed question types: ${input.types.join(", ")}.

Honesty Rule: Do not invent facts, names, or statistics not mentioned in the source. If the source material lacks details for the requested question count, return only as many high-quality questions as possible. All MCQ questions must have exactly 4 plausible options, with exactly one correct option. True/False questions must have options ['True', 'False'] and correctIndex corresponding to the correct answer. Fill-in-the-blank questions must have '_____' in the prompt and correctIndex as -1, with acceptable answers in acceptableAnswers.`,
      prompt: input.text,
    }),
  },

  "quiz-image": {
    mode: "object",
    inputSchema: z.object({
      image: imageField,
      count: z.number().int().min(1).max(30),
      types: z.array(questionTypeSchema).min(1),
      difficulty: difficultySchema,
      audience: audienceSchema,
    }),
    outputSchema: quizOutputSchema,
    build: (input) => ({
      system: `You are an expert quiz generator working from an IMAGE (a photo, screenshot, diagram, chart, slide, or scanned page). Generate a set of ${input.count} questions based ONLY on what is actually visible in the image — its text, labels, figures, diagrams, and data.
Difficulty target: ${input.difficulty}.
Target audience level: ${input.audience}.
Allowed question types: ${input.types.join(", ")}.

Honesty Rule: Do not invent facts, names, or statistics that are not visible in the image. If the image lacks enough content for the requested count, return only as many high-quality questions as the image supports. If the image contains no readable educational content, return an empty questions array. All MCQ questions must have exactly 4 plausible options with exactly one correct option. True/False questions must have options ['True', 'False'] and correctIndex for the correct answer. Fill-in-the-blank questions must have '_____' in the prompt and correctIndex -1, with acceptable answers in acceptableAnswers.`,
      prompt: "Generate the quiz from the attached image.",
      images: [input.image],
    }),
  },

  flashcards: {
    mode: "object",
    inputSchema: z.object({
      text: textField,
      count: z.number().int().min(1).max(40),
    }),
    outputSchema: flashcardOutputSchema,
    build: (input) => ({
      system: `You are a study card developer. Extract up to ${input.count} key terms, concepts, or definition pairs from the text to form high-quality flashcards.
Ensure flashcards are clear, concise, and focused on active recall. Front should ask a question or name a concept; Back should provide the definition or answer.
Honesty Rule: Rely only on facts in the provided text.`,
      prompt: input.text,
    }),
  },

  summary: {
    mode: "object",
    inputSchema: z.object({
      text: textField,
    }),
    outputSchema: summaryOutputSchema,
    build: (input) => ({
      system: `Summarize the user's text and extract the top key concepts. Write a concise, readable summary and extract terms with their definitions. Do not invent any facts not present in the text.`,
      prompt: input.text,
    }),
  },

  explain: {
    mode: "object",
    inputSchema: z.object({
      prompt: promptField,
      options: optionsField,
      correctIndex: z.number().int().min(-1).max(MAX_OPTIONS),
      acceptableAnswers: acceptableField,
      type: questionTypeSchema,
      userAnswer: z
        .union([z.string().max(MAX_ANSWER_CHARS), z.number().int()])
        .nullable(),
    }),
    outputSchema: explainOutputSchema,
    build: (input) => {
      const qDesc = `Question: "${input.prompt}"
Type: ${input.type}
Options: ${JSON.stringify(input.options)}
Correct index: ${input.correctIndex}
Acceptable answers: ${JSON.stringify(input.acceptableAnswers)}
User's Answer: ${input.userAnswer !== null ? JSON.stringify(input.userAnswer) : "None"}`;

      return {
        system: `You are an educational tutor. Analyze the given question and the user's response. Provide a helpful hint (without giving away the answer) and a detailed, clear explanation of why the correct answer is right and why the user's answer (if wrong or provided) is correct or incorrect. Do not refer to indexes like "index 0", use the actual option text when explaining.`,
        prompt: qDesc,
      };
    },
  },

  "weak-topics": {
    mode: "object",
    inputSchema: z.object({
      results: z
        .array(
          z.object({
            prompt: promptField,
            type: questionTypeSchema,
            correct: z.boolean(),
          })
        )
        .min(1, "No results to analyze.")
        .max(MAX_RESULTS),
    }),
    outputSchema: weakTopicsOutputSchema,
    build: (input) => {
      const resultsText = input.results
        .map((r: any) => `- [${r.correct ? "CORRECT" : "INCORRECT"}] (${r.type}) Question: "${r.prompt}"`)
        .join("\n");

      return {
        system: `You are a learning strategist. Analyze the user's quiz results to identify weak topic areas, evaluate their performance, and outline concrete revision tasks.
Group the analysis into high-level concepts and determine the user's strength ("weak", "medium", or "strong") in each concept based on which questions they missed. Provide actionable, supportive guidance and tasks.`,
        prompt: `Here are the quiz results:\n${resultsText}`,
      };
    },
  },

  "regenerate-one": {
    mode: "object",
    inputSchema: z.object({
      text: textField,
      type: questionTypeSchema,
      difficulty: difficultySchema,
      existingPrompts: z.array(z.string().max(MAX_PROMPT_CHARS)).max(MAX_EXISTING_PROMPTS),
    }),
    outputSchema: aiQuestionSchema,
    build: (input) => ({
      system: `You are an expert quiz generator. Generate exactly ONE new question of type "${input.type}" based on the text.
Difficulty target: ${input.difficulty}.
Crucial Constraint: The new question must NOT be similar to any of these existing questions:
${input.existingPrompts.map((p: string) => `- "${p}"`).join("\n")}

Ensure it is a unique question covering a different sentence or concept in the text. Return a single question matching the schema.`,
      prompt: input.text,
    }),
  },
};

export function getSpec(id: CapabilityId): CapabilitySpec {
  return SPECS[id];
}
